### ISSUE TITLE
Slides Index – Things to do before launching the 1.4.0 version

### ISSUE THREAD

**Issue by jlantunez** [webslides/WebSlides#88]
**WebSlides 1.4.0 automatically will create a slides index**:

- [x] Find a way to reduce the loading time.
- [x] Media queries for portrait and landscape orientations.
- [x] Highlight the current slide.
- [x] Scroll to current slide when zooming in (scroll doesn't work in Chrome)
- [x]  Set the height of slides

**Comment by displaynone** [comment]
Scroll to current slide when zooming in implemented in c109276
